// This file was generated by Prisma, and assumes you have installed the following:
// npm install --save-dev prisma dotenv
import "dotenv/config";
import { defineConfig } from "prisma/config";
import { resolveMigrationUrl } from "./tools/deploy/migrationUrl.mjs";

export default defineConfig({
  schema: "prisma/schema.prisma",
  migrations: {
    path: "prisma/migrations",
  },
  datasource: {
    // Migrate serialises itself with a session-scoped advisory lock, which a
    // transaction-mode pooler cannot hold across statements — every deploy then
    // times out acquiring pg_advisory_lock(72707369). Point DIRECT_URL at the
    // unpooled endpoint; without it this falls back to DATABASE_URL as before.
    url: resolveMigrationUrl(process.env),
  },
});
