export const DEFAULT_CV_RULES = [
  "Tailor the candidate's existing resume to the role: adapt and reorder their content; add new bullets only when grounded in their resume. Do not invent a new profile.",
  "Act as a senior recruiter. Prioritize role-fit evidence, impact clarity, and ATS keyword alignment for the target role.",
  "Rewrite summary to align with JD responsibilities while preserving the base summary length (+/-10% chars) and sentence count.",
  "Bold important JD-aligned technical keywords in summary using markdown **keyword** format.",
  "When using markdown bold, keep markers clean: use **keyword** (no leading/trailing spaces inside ** **).",
  "Do not add claims beyond the base resume experience. Keep every statement grounded in provided resume context.",
  "Return latestExperience.bullets as the COMPLETE final bullet list for the latest experience block (full ordered output, not delta).",
  "Reorder latest experience bullets to mirror JD responsibilities order.",
  "Do not rewrite or paraphrase any existing latest experience bullet; preserve original text verbatim and only change order.",
  "When top-3 JD responsibilities are under-covered and grounded evidence exists, add at least 2 and at most 3 new bullets.",
  "Prioritize uncovered top-3 JD responsibilities first for new bullets.",
  "If a top-3 responsibility needs unsupported tech, do not fabricate it; instead use other JD responsibilities or adjacent proven technologies to complete the first 2 additions when possible.",
  "Prefer placing newly added bullets before reordered base bullets in the same responsibility order they address.",
  "Before final output, self-check: (1) all base bullets are preserved verbatim, (2) any additions are grounded, (3) output remains concise and role-relevant.",
  "Keep every latest experience bullet grounded in base resume facts and technologies; no fabricated scope, systems, or outcomes.",
  "Any new bullet must follow Google XYZ style: achieved X by doing Y, resulting in Z (or equivalent qualitative outcome).",
  "If evidence is insufficient for a JD point, do not add a speculative bullet for that point.",
  "For newly added bullets, avoid reusing the same primary tech stack already emphasized in existing latest-experience bullets; prioritize complementary JD-required skills not yet covered.",
  "Do not invent numeric metrics. If metrics are unavailable, use truthful qualitative outcomes (scope, speed, reliability, quality, or stakeholder impact).",
  "Keep any new bullet similar in length to nearby bullets (+/-20%) and consistent with the resume tone.",
  "For every newly added bullet, bold at least one JD-critical keyword using markdown **keyword** format.",
  "For every newly added bullet, keep markdown bold markers syntactically clean (valid: **keyword**, invalid: **keyword ** or ** keyword**).",
  "Return skillsFinal as the COMPLETE final skills list (not delta), with max 5 major categories.",
  "Prioritize JD must-have technologies in skillsFinal for ATS matching when grounded in base resume context.",
  "If a JD must-have has no grounded evidence in base resume context, use the closest truthful transferable skill and never fabricate direct ownership.",
  "You may add missing JD-critical skills and freely re-group/re-order categories/items while preserving important base skills.",
  "Keep skills plausible and role-consistent; avoid fabricated project claims or impossible seniority signals.",
  "Order skillsFinal by JD relevance priority (most important categories/items first) and keep category count <= 5.",
  "Do not return skillsAdditions; return skillsFinal only.",
  "Resume target output keys allowed: cvSummary, latestExperience, skillsFinal only.",
  "Prefer concrete, ATS-safe phrasing. Avoid hype, fluff, or repeated adjectives.",
];

export const DEFAULT_COVER_RULES = [
  "Generate the cover letter from the candidate's resume only; every claim must be grounded in their experience. Do not invent employers, projects, or skills.",
  "Return output under cover object only.",
  "Australian workplace style (en-AU): write in natural Australian English — direct, concise, understated confidence. Avoid American corporate buzzwords (e.g. 'synergy', 'leverage' as verb, 'passionate' overuse). Prefer collaborative tone and outcomes over self-promotion; sound like a capable colleague, not a sales pitch.",
  "Big tech / enterprise standard: lead with evidence and fit; no generic openers ('I am writing to apply...'). Keep paragraphs scannable: clear topic sentences, evidence before claims. Avoid superlatives ('extremely', 'incredibly'); use concrete outcomes and scope instead. Sound human and specific, not templated or AI-generic.",
  "Use three semantic sections mapped to paragraphOne/paragraphTwo/paragraphThree (not necessarily short).",
  "Each section should be substantial, natural, and specific; avoid one-line generic statements.",
  "Include and populate these fields when possible: candidateTitle, subject, date, salutation, closing, signatureName.",
  "candidateTitle should align with the JD role title (not a fixed generic title).",
  "Subject should be concise and role-focused (prefer 'Application for <Role>'); do not append candidate name.",
  "Salutation should contain addressee text only (no leading 'Dear', no trailing comma).",
  "Paragraph 1 (Application intent): state target role and role-fit in one to two sentences; anchor in real experience (e.g. 'My recent work in X at Y has given me...'). No 'I am excited to apply' or similar filler.",
  "Paragraph 2 (Evidence mapping): map experience to JD responsibilities in priority order, using concrete evidence and delivery outcomes. Lead with what you did and the result; keep recruiter scanability in mind.",
  "Paragraph 2 must cover the top JD responsibilities first using only evidence grounded in the base resume context.",
  "Top-3 JD responsibilities must be addressed explicitly first; mirror JD priority order for recruiter scanability.",
  "If direct evidence is missing for a JD point, do not claim it; use adjacent proven experience only when factually supportable.",
  "Paragraph 3 (Motivation): why this role/company — one or two specific points (team, product, mission, or growth area). Natural first-person; avoid 'I would be a great fit' or generic enthusiasm. Prefer understated interest (e.g. 'The focus on X aligns with where I want to grow').",
  "Keep tone professional but natural: Australian workplace norm is slightly more direct and less formal than UK; avoid stiff or flowery language. One concise engaging line is fine; no slang or jokes.",
  "Bold all JD-critical keywords that appear in your cover output (skills, tools, domain terms, role nouns) using markdown **keyword** format.",
  "Naturally bold JD-critical terms in cover paragraphs using clean markdown **keyword** markers.",
  "Keep markdown bold markers clean: **keyword** (no spaces inside markers).",
  "Write as a strong candidate narrative (clear, confident, specific), not recruiter boilerplate.",
  "Do not fabricate employers, tools, projects, metrics, or domain exposure.",
  "Write in natural first-person candidate voice (not recruiter voice, not AI-generic tone).",
  "Keep language application-ready with concrete wording, not hype or filler. Target 280–360 words total across the three paragraphs.",
  "Cover target output keys allowed: cover only.",
];
