// AUTO-GENERATED from au.seek.com live v5 search (2026-06-06). DO NOT edit by hand.
// Harvested up to 5 pages/parent; subclass kept only when its sibling
// classification.id matches the queried parent (jobs are cross-listed).
// Long-tail subclasses with no live postings in the sample window may be absent.

export const SEEK_SUBCLASSIFICATIONS: Record<string, ReadonlyArray<{ id: string; label: string }>> = {
  "1200": [
    { id: "6140", label: "Accounts Officers/Clerks" },
    { id: "1303", label: "Accounts Payable" },
    { id: "6141", label: "Accounts Receivable/Credit Control" },
    { id: "6143", label: "Analysis & Reporting" },
    { id: "6142", label: "Assistant Accountants" },
    { id: "6145", label: "Audit - Internal" },
    { id: "6146", label: "Bookkeeping & Small Practice Accounting" },
    { id: "6147", label: "Business Services & Corporate Advisory" },
    { id: "6150", label: "Cost Accounting" },
    { id: "6151", label: "Financial Accounting & Reporting" },
    { id: "6152", label: "Financial Managers & Controllers" },
    { id: "6155", label: "Inventory & Fixed Assets" },
    { id: "6156", label: "Management" },
    { id: "6157", label: "Management Accounting & Budgeting" },
    { id: "6162", label: "Other" },
    { id: "1468", label: "Payroll" },
    { id: "6159", label: "Systems Accounting & IT Audit" },
    { id: "6160", label: "Taxation" },
  ],
  "6251": [
    { id: "6252", label: "Administrative Assistants" },
    { id: "6253", label: "Client & Sales Administration" },
    { id: "6254", label: "Contracts Administration" },
    { id: "6255", label: "Data Entry & Word Processing" },
    { id: "6256", label: "Office Management" },
    { id: "6260", label: "Other" },
    { id: "6257", label: "PA, EA & Secretarial" },
    { id: "6258", label: "Receptionists" },
    { id: "6259", label: "Records Management & Document Control" },
  ],
  "6304": [
    { id: "6305", label: "Agency Account Management" },
    { id: "6306", label: "Art Direction" },
    { id: "6307", label: "Editing & Publishing" },
    { id: "6308", label: "Event Management" },
    { id: "6309", label: "Journalism & Writing" },
    { id: "6310", label: "Management" },
    { id: "6311", label: "Media Strategy, Planning & Buying" },
    { id: "6316", label: "Other" },
    { id: "6312", label: "Performing Arts" },
    { id: "6313", label: "Photography" },
    { id: "6314", label: "Programming & Production" },
    { id: "6315", label: "Promotions" },
  ],
  "1203": [
    { id: "6174", label: "Account & Relationship Management" },
    { id: "6175", label: "Analysis & Reporting" },
    { id: "6177", label: "Banking - Business" },
    { id: "6178", label: "Banking - Corporate & Institutional" },
    { id: "6176", label: "Banking - Retail/Branch" },
    { id: "1352", label: "Client Services" },
    { id: "6179", label: "Compliance & Risk" },
    { id: "6180", label: "Corporate Finance & Investment Banking" },
    { id: "6181", label: "Credit" },
    { id: "1392", label: "Financial Planning" },
    { id: "1404", label: "Funds Management" },
    { id: "6182", label: "Management" },
    { id: "6183", label: "Mortgages" },
    { id: "6187", label: "Other" },
    { id: "6184", label: "Settlements" },
    { id: "6185", label: "Stockbroking & Trading" },
    { id: "6186", label: "Treasury" },
  ],
  "1204": [
    { id: "6084", label: "Collections" },
    { id: "6085", label: "Customer Service - Call Centre" },
    { id: "6086", label: "Customer Service - Customer Facing" },
    { id: "6087", label: "Management & Support" },
    { id: "6091", label: "Other" },
    { id: "6088", label: "Sales - Inbound" },
    { id: "6089", label: "Sales - Outbound" },
    { id: "6090", label: "Supervisors/Team Leaders" },
  ],
  "6163": [
    { id: "6164", label: "Aged & Disability Support" },
    { id: "6165", label: "Child Welfare, Youth & Family Services" },
    { id: "6166", label: "Community Development" },
    { id: "6167", label: "Employment Services" },
    { id: "6168", label: "Fundraising" },
    { id: "6169", label: "Housing & Homelessness Services" },
    { id: "6170", label: "Indigenous & Multicultural Services" },
    { id: "6171", label: "Management" },
    { id: "6173", label: "Other" },
    { id: "6172", label: "Volunteer Coordination & Support" },
  ],
  "1206": [
    { id: "6113", label: "Contracts Management" },
    { id: "1387", label: "Estimating" },
    { id: "6114", label: "Foreperson/Supervisors" },
    { id: "6115", label: "Health, Safety & Environment" },
    { id: "6116", label: "Management" },
    { id: "6122", label: "Other" },
    { id: "6117", label: "Planning & Scheduling" },
    { id: "6118", label: "Plant & Machinery Operators" },
    { id: "6119", label: "Project Management" },
    { id: "6120", label: "Quality Assurance & Control" },
    { id: "6121", label: "Surveying" },
  ],
  "6263": [
    { id: "6265", label: "Architectural Drafting" },
    { id: "6264", label: "Architecture" },
    { id: "6267", label: "Fashion & Textile Design" },
    { id: "6268", label: "Graphic Design" },
    { id: "6269", label: "Industrial Design" },
    { id: "6270", label: "Interior Design" },
    { id: "6271", label: "Landscape Architecture" },
    { id: "6274", label: "Other" },
    { id: "6272", label: "Urban Design & Planning" },
    { id: "6273", label: "Web & Interaction Design" },
  ],
  "6123": [
    { id: "6124", label: "Childcare & Outside School Hours Care" },
    { id: "6125", label: "Library Services & Information Management" },
    { id: "6126", label: "Management - Schools" },
    { id: "6127", label: "Management - Universities" },
    { id: "6128", label: "Management - Vocational" },
    { id: "6139", label: "Other" },
    { id: "6129", label: "Research & Fellowships" },
    { id: "6130", label: "Student Services" },
    { id: "6132", label: "Teaching - Early Childhood" },
    { id: "6133", label: "Teaching - Primary" },
    { id: "6134", label: "Teaching - Secondary" },
    { id: "6135", label: "Teaching - Tertiary" },
    { id: "6136", label: "Teaching - Vocational" },
    { id: "6131", label: "Teaching Aides & Special Needs" },
    { id: "6137", label: "Tutoring" },
    { id: "6138", label: "Workplace Training & Assessment" },
  ],
  "1209": [
    { id: "6022", label: "Aerospace Engineering" },
    { id: "6023", label: "Automotive Engineering" },
    { id: "6024", label: "Building Services Engineering" },
    { id: "6026", label: "Chemical Engineering" },
    { id: "6027", label: "Civil/Structural Engineering" },
    { id: "6028", label: "Electrical/Electronic Engineering" },
    { id: "6025", label: "Engineering Drafting" },
    { id: "6029", label: "Environmental Engineering" },
    { id: "6030", label: "Field Engineering" },
    { id: "6031", label: "Industrial Engineering" },
    { id: "6032", label: "Maintenance" },
    { id: "6033", label: "Management" },
    { id: "6034", label: "Materials Handling Engineering" },
    { id: "6035", label: "Mechanical Engineering" },
    { id: "6042", label: "Other" },
    { id: "6036", label: "Process Engineering" },
    { id: "6038", label: "Project Engineering" },
    { id: "6037", label: "Project Management" },
    { id: "6039", label: "Supervisors" },
    { id: "6040", label: "Systems Engineering" },
    { id: "6041", label: "Water & Waste Engineering" },
  ],
  "6205": [
    { id: "6206", label: "Agronomy & Farm Services" },
    { id: "6207", label: "Conservation, Parks & Wildlife" },
    { id: "6208", label: "Farm Labour" },
    { id: "6209", label: "Farm Management" },
    { id: "6210", label: "Fishing & Aquaculture" },
    { id: "6211", label: "Horticulture" },
    { id: "6214", label: "Other" },
    { id: "6212", label: "Veterinary Services & Animal Welfare" },
    { id: "6213", label: "Winery & Viticulture" },
  ],
  "1210": [
    { id: "1378", label: "Emergency Services" },
    { id: "6356", label: "Government" },
    { id: "1409", label: "Government - Federal" },
    { id: "1410", label: "Government - Local" },
    { id: "1411", label: "Government - State" },
    { id: "6357", label: "Local Government" },
    { id: "1450", label: "Navy" },
    { id: "6361", label: "Other" },
    { id: "6359", label: "Police & Corrections" },
    { id: "6360", label: "Policy, Planning & Regulation" },
    { id: "6358", label: "Regional Council" },
  ],
  "1211": [
    { id: "6329", label: "Ambulance/Paramedics" },
    { id: "1353", label: "Clinical/Medical Research" },
    { id: "1372", label: "Dental" },
    { id: "6331", label: "Dieticians" },
    { id: "1386", label: "Environmental Services" },
    { id: "6333", label: "Management" },
    { id: "6334", label: "Medical Administration" },
    { id: "6335", label: "Medical Imaging" },
    { id: "6336", label: "Medical Specialists" },
    { id: "6338", label: "Nursing - A&E, Critical Care & ICU" },
    { id: "6339", label: "Nursing - Aged Care" },
    { id: "6340", label: "Nursing - Community, Maternal & Child Health" },
    { id: "6341", label: "Nursing - Educators & Facilitators" },
    { id: "6342", label: "Nursing - General Medical & Surgical" },
    { id: "6344", label: "Nursing - Management" },
    { id: "6345", label: "Nursing - Midwifery, Neo-Natal, SCN & NICU" },
    { id: "6347", label: "Nursing - Psych, Forensic & Correctional Health" },
    { id: "6348", label: "Nursing - Theatre & Recovery" },
    { id: "6349", label: "Optical" },
    { id: "6355", label: "Other" },
    { id: "1467", label: "Pathology" },
    { id: "6350", label: "Pharmaceuticals & Medical Devices" },
    { id: "1470", label: "Pharmacy" },
    { id: "6352", label: "Physiotherapy, OT & Rehabilitation" },
    { id: "6351", label: "Psychology, Counselling & Social Work" },
    { id: "6353", label: "Sales" },
  ],
  "1212": [
    { id: "1315", label: "Airlines" },
    { id: "1332", label: "Bar & Beverage Staff" },
    { id: "6052", label: "Chefs/Cooks" },
    { id: "6053", label: "Front Office & Guest Services" },
    { id: "1405", label: "Gaming" },
    { id: "1415", label: "Housekeeping" },
    { id: "6054", label: "Kitchen & Sandwich Hands" },
    { id: "6055", label: "Management" },
    { id: "6057", label: "Other" },
    { id: "6056", label: "Reservations" },
    { id: "1537", label: "Tour Guides" },
    { id: "1542", label: "Travel Agents/Consultants" },
    { id: "1549", label: "Waiting Staff" },
  ],
  "6317": [
    { id: "6318", label: "Consulting & Generalist HR" },
    { id: "6319", label: "Industrial & Employee Relations" },
    { id: "6321", label: "Management - Internal" },
    { id: "6323", label: "Organisational Development" },
    { id: "6328", label: "Other" },
    { id: "6324", label: "Recruitment - Agency" },
    { id: "6325", label: "Recruitment - Internal" },
    { id: "6327", label: "Training & Development" },
  ],
  "6281": [
    { id: "6282", label: "Architects" },
    { id: "6283", label: "Business/Systems Analysts" },
    { id: "6286", label: "Database Development & Administration" },
    { id: "6287", label: "Developers/Programmers" },
    { id: "6288", label: "Engineering - Hardware" },
    { id: "6289", label: "Engineering - Network" },
    { id: "6290", label: "Engineering - Software" },
    { id: "6291", label: "Help Desk & IT Support" },
    { id: "6292", label: "Management" },
    { id: "6293", label: "Networks & Systems Administration" },
    { id: "6303", label: "Other" },
    { id: "6294", label: "Product Management & Development" },
    { id: "6295", label: "Programme & Project Management" },
    { id: "6297", label: "Security" },
    { id: "6298", label: "Team Leaders" },
    { id: "6300", label: "Telecommunications" },
    { id: "6301", label: "Testing & Quality Assurance" },
    { id: "6302", label: "Web Development & Production" },
  ],
  "1216": [
    { id: "6188", label: "Banking & Finance Law" },
    { id: "6190", label: "Construction Law" },
    { id: "6191", label: "Corporate & Commercial Law" },
    { id: "6189", label: "Criminal & Civil Law" },
    { id: "6192", label: "Environment & Planning Law" },
    { id: "6193", label: "Family Law" },
    { id: "6194", label: "Generalists - In-house" },
    { id: "6195", label: "Generalists - Law Firm" },
    { id: "6196", label: "Industrial Relations & Employment Law" },
    { id: "6197", label: "Insurance & Superannuation Law" },
    { id: "6198", label: "Intellectual Property Law" },
    { id: "1429", label: "Law Clerks & Paralegals" },
    { id: "6199", label: "Legal Practice Management" },
    { id: "1431", label: "Legal Secretaries" },
    { id: "6200", label: "Litigation & Dispute Resolution" },
    { id: "6204", label: "Other" },
    { id: "6201", label: "Personal Injury Law" },
    { id: "6202", label: "Property Law" },
    { id: "6203", label: "Tax Law" },
  ],
  "6092": [
    { id: "6093", label: "Assembly & Process Work" },
    { id: "6094", label: "Aviation Services" },
    { id: "6096", label: "Couriers, Drivers & Postal Services" },
    { id: "6097", label: "Fleet Management" },
    { id: "6098", label: "Freight/Cargo Forwarding" },
    { id: "6099", label: "Import/Export & Customs" },
    { id: "6101", label: "Machine Operators" },
    { id: "6102", label: "Management" },
    { id: "6112", label: "Other" },
    { id: "6105", label: "Pickers & Packers" },
    { id: "6103", label: "Production, Planning & Scheduling" },
    { id: "6100", label: "Public Transport & Taxi Services" },
    { id: "6109", label: "Purchasing, Procurement & Inventory" },
    { id: "6111", label: "Road Transport" },
    { id: "6107", label: "Team Leaders/Supervisors" },
    { id: "6108", label: "Warehousing, Storage & Distribution" },
  ],
  "6008": [
    { id: "6009", label: "Brand Management" },
    { id: "6010", label: "Digital & Search Marketing" },
    { id: "6011", label: "Direct Marketing & CRM" },
    { id: "6012", label: "Event Management" },
    { id: "6013", label: "Internal Communications" },
    { id: "6017", label: "Management" },
    { id: "6014", label: "Market Research & Analysis" },
    { id: "6015", label: "Marketing Assistants/Coordinators" },
    { id: "6016", label: "Marketing Communications" },
    { id: "6021", label: "Other" },
    { id: "6018", label: "Product Management & Development" },
    { id: "6019", label: "Public Relations & Corporate Affairs" },
    { id: "6020", label: "Trade Marketing" },
  ],
  "6058": [
    { id: "6059", label: "Analysis & Reporting" },
    { id: "6060", label: "Health, Safety & Environment" },
    { id: "6061", label: "Management" },
    { id: "6062", label: "Mining - Drill & Blast" },
    { id: "6063", label: "Mining - Engineering & Maintenance" },
    { id: "6064", label: "Mining - Exploration & Geoscience" },
    { id: "6066", label: "Mining - Operations" },
    { id: "6065", label: "Mining - Processing" },
    { id: "6073", label: "Natural Resources & Water" },
    { id: "6067", label: "Oil & Gas - Drilling" },
    { id: "6068", label: "Oil & Gas - Engineering & Maintenance" },
    { id: "6071", label: "Oil & Gas - Operations" },
    { id: "6075", label: "Other" },
    { id: "6072", label: "Power Generation & Distribution" },
    { id: "6074", label: "Surveying" },
  ],
  "1220": [
    { id: "6371", label: "Administration" },
    { id: "6001", label: "Analysts" },
    { id: "6002", label: "Body Corporate & Facilities Management" },
    { id: "6003", label: "Commercial Sales, Leasing & Property Mgmt" },
    { id: "6007", label: "Other" },
    { id: "6004", label: "Residential Leasing & Property Management" },
    { id: "6005", label: "Residential Sales" },
    { id: "6006", label: "Retail & Property Development" },
    { id: "1546", label: "Valuation" },
  ],
  "6043": [
    { id: "6044", label: "Buying" },
    { id: "6045", label: "Management - Area/Multi-site" },
    { id: "6046", label: "Management - Department/Assistant" },
    { id: "6047", label: "Management - Store" },
    { id: "6048", label: "Merchandisers" },
    { id: "6051", label: "Other" },
    { id: "6049", label: "Planning" },
    { id: "6050", label: "Retail Assistants" },
  ],
  "6362": [
    { id: "6363", label: "Account & Relationship Management" },
    { id: "6366", label: "Management" },
    { id: "6365", label: "New Business Development" },
    { id: "6369", label: "Other" },
    { id: "6367", label: "Sales Coordinators" },
    { id: "6368", label: "Sales Representatives/Consultants" },
  ],
  "1223": [
    { id: "6215", label: "Biological & Biomedical Sciences" },
    { id: "6216", label: "Biotechnology & Genetics" },
    { id: "6217", label: "Chemistry & Physics" },
    { id: "6218", label: "Environmental, Earth & Geosciences" },
    { id: "6219", label: "Food Technology & Safety" },
    { id: "6220", label: "Laboratory & Technical Services" },
    { id: "6221", label: "Materials Sciences" },
    { id: "6222", label: "Mathematics, Statistics & Information Sciences" },
    { id: "6225", label: "Other" },
    { id: "6224", label: "Quality Assurance & Control" },
  ],
  "1225": [
    { id: "1313", label: "Air Conditioning & Refrigeration" },
    { id: "1328", label: "Automotive Trades" },
    { id: "6227", label: "Building Trades" },
    { id: "1345", label: "Carpentry & Cabinet Making" },
    { id: "6229", label: "Cleaning Services" },
    { id: "6230", label: "Electricians" },
    { id: "6231", label: "Fitters, Turners & Machinists" },
    { id: "1406", label: "Gardening & Landscaping" },
    { id: "6234", label: "Labourers" },
    { id: "6236", label: "Maintenance & Handyperson Services" },
    { id: "6245", label: "Other" },
    { id: "6238", label: "Painters & Sign Writers" },
    { id: "6240", label: "Plumbers" },
    { id: "6241", label: "Security Services" },
    { id: "6243", label: "Technicians" },
  ],
};
